package com.overworldlabs.regions.bridge.runtime;

import java.util.Map;
import java.util.concurrent.ConcurrentHashMap;

/**
 * Registry for synthetic classes generated by Mixin (Accessors/Invokers).
 * Hytale's loader only sees files on disk, so we use this to serve in-memory classes.
 */
public final class SyntheticClassRegistry {
    private static final Map<String, byte[]> CLASSES = new ConcurrentHashMap<>();

    public static void register(String className, byte[] bytecode) {
        CLASSES.put(className.replace('/', '.'), bytecode);
    }

    public static byte[] get(String className) {
        return CLASSES.get(className.replace('/', '.'));
    }

    public static boolean has(String className) {
        return CLASSES.containsKey(className.replace('/', '.'));
    }
}
